# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QWidget
import MySQLdb as mdb
from PIL import Image
from pandas import io
import io
import base64

class Ui_ManWindow(QWidget,object):
    def getImage(self):
        fname = QFileDialog.getOpenFileName(self, 'Open file','c:\'', "Image files (*.jpg *.gif)")
        imagepath = fname[0]
        user = self.lineEdit1.text()
        password = self.lineEdit2.text()
        docname = self.lineEdit.text()
        file = open(imagepath, 'rb').read()
        file = base64.b64encode(file)
        db = mdb.connect('localhost', 'root', '', 'fastag')
        mycursor = db.cursor()
        args = (user, password, docname, file)
        query = 'INSERT INTO DOCUMS VALUES(%s ,%s, %s, %s)'
        mycursor.execute(query, args)


        db.commit()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.getImage())
        self.pushButton.setGeometry(QtCore.QRect(340, 160, 121, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 121, 31))
        self.label.setObjectName("label")
        self.label.setText("Enter your docname")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 40, 121, 16))
        self.label1.setObjectName("label1")
        self.label1.setText("Username")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(290, 40, 91, 21))
        self.label2.setObjectName("label2")
        self.label2.setText("Password")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(150, 30, 113, 31))
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(390, 30, 113, 31))
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 120, 181, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Browse Image"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ManWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
