# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from exitpoints import Ui_Dialog
from Travel import Ui_Window
from TravH import Ui_MWindow
from Acc import Ui_MainWindow
from deposit import Ui_MaWindow
from TravelAnalysis import Ui_aiWindow
from docvault import Ui_DWindow

class Ui_Login(object):
    def ex(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.ui.connect()
        self.Dialog.show()
    def exi(self):
        sys.exit(app.exec_())
    def trav(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Window()
        self.ui.setupUi(self.window)
        self.window.show()
    def TravH(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def acc(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def despo(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MaWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def Travanna(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_aiWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def docv(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DWindow()
        self.ui.setupUi(self.window)
        self.window.show()




    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 281)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.trav())
        self.pushButton.setGeometry(QtCore.QRect(30, 110, 93, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.acc())
        self.pushButton_2.setGeometry(QtCore.QRect(150, 110, 93, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.despo())
        self.pushButton_3.setGeometry(QtCore.QRect(280, 110, 93, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.TravH())
        self.pushButton_4.setGeometry(QtCore.QRect(410, 110, 93, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.exi())
        self.pushButton_5.setGeometry(QtCore.QRect(650, 110, 93, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.ex())
        self.pushButton_6.setGeometry(QtCore.QRect(530, 110, 93, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.Travanna())
        self.pushButton_7.setGeometry(QtCore.QRect(600, 190, 120, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setText("TRAVEL ANALYSIS")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.docv())
        self.pushButton_8.setGeometry(QtCore.QRect(120, 190, 120, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setText("FasTag-DOC VAULT")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.pushButton.setText(_translate("Login", "Travel"))
        self.pushButton_2.setText(_translate("Login", "view Account"))
        self.pushButton_3.setText(_translate("Login", "Deposit"))
        self.pushButton_4.setText(_translate("Login", "Travel History"))
        self.pushButton_5.setText(_translate("Login", "exit"))
        self.pushButton_6.setText(_translate("Login", "exit points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
