# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Travel.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import MySQLdb as mdb


class Ui_Window(object):
    def Travel(self):
        vno = self.lineEdit_2.text()
        exipoint = self.lineEdit.text()
        db = mdb.connect('localhost', 'root', '', 'fastag')
        cur = db.cursor()
        cur.execute("SELECT balance from users WHERE vno like'"+vno+"'")
        result = cur.fetchone()
        cur.execute("SELECT cost from cost WHERE exits like'"+exipoint+"'")
        result2 = cur.fetchone()
        t = int(result[0])-int(result2[0])
        self.textEdit.append(" "+str(t)+" amount is available")
        cur.execute("UPDATE users SET balance ='"+str(t)+"'WHERE vno like '"+vno+"'")
        cur.execute("SELECT username from users WHERE vno like'"+vno+"'")
        result3 = cur.fetchone()
        cur.execute("INSERT INTO travelh(username,entrypoint,exitpoint,charge)"
                              "VALUES('%s', '%d', '%d', '%d')" % (''.join(result3[0]), int(0), int(exipoint), int(result2[0])))
        db.commit()






    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 70, 231, 61))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 90, 151, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.Travel())
        self.pushButton.setGeometry(QtCore.QRect(410, 220, 181, 71))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 170, 221, 87))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 101, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 191, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 20, 161, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Enter your exit point</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "submit"))
        self.label_2.setText(_translate("MainWindow", "Available balance"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Enter vechile no :</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
