# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vechile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
import numpy as np
import MySQLdb as mdb


class Ui_VWindow(object):
    def VechAna(self):
        vtype = self.lineEdit.text()
        db = mdb.connect('localhost', 'root', '', 'fastag')
        mycursor = db.cursor()
        query = "SELECT username from users WHERE vtype like'"+vtype+"'"
        mycursor.execute(query)
        result = mycursor.fetchall()
        one = 0
        two = 0
        three = 0
        four = 0
        five = 0
        for i in result:
            query2 = "SELECT count(exitpoint) from travelh where exitpoint like'"+str(1)+"'and username like'"+i[0]+"'"
            mycursor.execute(query2)
            result2 = mycursor.fetchone()
            one = one+int(result2[0])
        for i in result:
            query3 = "SELECT count(exitpoint) from travelh where exitpoint like'"+str(2)+"'and username like'"+i[0]+"'"
            mycursor.execute(query3)
            result3 = mycursor.fetchone()
            two = two+int(result3[0])
        for i in result:
            query4 = "SELECT count(exitpoint) from travelh where exitpoint like'"+str(3)+"'and username like'"+i[0]+"'"
            mycursor.execute(query4)
            result4 = mycursor.fetchone()
            three = three+int(result4[0])
        for i in result:
            query5 = "SELECT count(exitpoint) from travelh where exitpoint like'"+str(4)+"'and username like'"+i[0]+"'"
            mycursor.execute(query5)
            result5 = mycursor.fetchone()
            four = four+int(result5[0])
        for i in result:
            query6 = "SELECT count(exitpoint) from travelh where exitpoint like'"+str(5)+"'and username like'"+i[0]+"'"
            mycursor.execute(query6)
            result6 = mycursor.fetchone()
            five = five+int(result6[0])


        y = np.array([one, two, three, four, five])
        mylabels = ["Exit1", "Exit2", "Exit3", "Exit4", "Exit5"]
        myexplode = [0.1, 0.15, 0.2, 0.25, 0.3]
        plt.pie(y, labels=mylabels, explode=myexplode)
        plt.legend()
        plt.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 265)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 201, 61))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 60, 181, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.VechAna())
        self.pushButton.setGeometry(QtCore.QRect(160, 180, 121, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Enter vechile type :</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_VWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
